### ISSUE TITLE
Dbusmenu Bindings for gtk4

### ISSUE THREAD

**Issue by coderPaddyS** [ralismark/dbusmenu-rs#1]
Hey, thanks for creating those gtk3 bindings for rust.
As I'm not experienced at all with rust ffi, would it be possible for you to adapt the bindings for gtk4?

**Comment by ralismark** [comment]
This library is simply rust bindings for https://github.com/AyatanaIndicators/libdbusmenu. There isn't a gtk4 version of that library, only a gtk3 one, so I can't make a version of dbusmenu-rs for gtk4.
